# Generated by Django 2.1.7 on 2019-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='id',
        ),
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False, verbose_name='权限code码'),
        ),
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='permission',
            name='main_menu',
            field=models.BooleanField(default=True, verbose_name='是否是主菜单'),
        ),
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(default='', max_length=128, verbose_name='含正则的URL'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='rbac.Permission', verbose_name='拥有的所有权限'),
        ),
    ]
